import type { Destination, StudentDocument, AdminDocument } from "./types";

export const destinations: Destination[] = [
    {
        id: "dest-1",
        categoryCode: "LPPM-01",
        name: "Lembaga Penelitian dan Pengabdian",
        faculty: "Lembaga Universitas",
        description: "Pusat penerimaan dokumen penelitian dan pengabdian masyarakat.",
        documentCount: 24,
        status: "open",
        acceptedDocuments: ["Proposal Penelitian", "Laporan Akhir Pengabdian", "Paten/HKI"],
    },
    {
        id: "dest-2",
        categoryCode: "TU-KOM-02",
        name: "Tata Usaha Ilmu Komputer",
        faculty: "Fakultas MIPA",
        description: "Administrasi akademik program studi Ilmu Komputer",
        documentCount: 12,
        status: "open",
        acceptedDocuments: ["KRS/Tahunan", "Surat Keterangan Aktif", "Transkrip Sementara"],
    },
    {
        id: "dest-3",
        categoryCode: "DEK-MIPA-03",
        name: "Dekanat Fakultas MIPA",
        faculty: "Fakultas MIPA",
        description: "Kantor Dekan dan Wakil Dekan Fakultas MIPA",
        documentCount: 5,
        status: "closed",
        acceptedDocuments: ["Pengajuan Beasiswa", "Surat Izin PKL", "Lembar Pengesahan"],
    },
    {
        id: "dest-4",
        categoryCode: "BAK-04",
        name: "Biro Administrasi Akademik",
        faculty: "Rektorat",
        description: "Biro Administrasi Akademik dan Kemahasiswaan",
        documentCount: 19,
        status: "open",
        acceptedDocuments: ["Legalisir Ijazah", "Surat Cuti Akademik", "Pencetakan KTM"],
    },
    {
        id: "dest-5",
        categoryCode: "LAB-ICT-05",
        name: "Laboratorium ICT",
        faculty: "Fakultas MIPA",
        description: "Pusat penelitian Teknologi Informasi dan Komunikasi",
        documentCount: 8,
        status: "open",
        acceptedDocuments: ["Peminjaman Alat", "Akses Server", "Sertifikasi IT"],
    },
    {
        id: "dest-6",
        categoryCode: "PERPUS-06",
        name: "Perpustakaan Pusat",
        faculty: "Universitas",
        description: "Layanan administrasi keanggotaan dan bebas pustaka",
        documentCount: 31,
        status: "open",
        acceptedDocuments: ["Bebas Pustaka", "Keanggotaan Baru", "Denda Buku"],
    },
    {
        id: "dest-7",
        categoryCode: "FT-TU-07",
        name: "Tata Usaha Teknik Sipil",
        faculty: "Fakultas Teknik",
        description: "Layanan mahasiswa jurusan Teknik Sipil",
        documentCount: 15,
        status: "closed",
        acceptedDocuments: ["Laporan Praktek", "Yudisium", "Cuti Studi"],
    },
    {
        id: "dest-8",
        categoryCode: "FK-ADM-08",
        name: "Admin Fakultas Kedokteran",
        faculty: "Fakultas Kedokteran",
        description: "Layanan administrasi pendidikan dokter",
        documentCount: 42,
        status: "open",
        acceptedDocuments: ["Izin Koas", "Kelengkapan UKMPPD", "Surat Keterangan"],
    },
];

export const studentDocuments: StudentDocument[] = [
    {
        id: "doc-1",
        destinationName: "LPPM Universitas",
        documentType: "Surat Pengantar Penelitian",
        submittedAt: "26 Feb 2026, 09:15",
        status: "Diproses",
        trackingId: "HYD-2026-001",
    },
    {
        id: "doc-2",
        destinationName: "Tata Usaha Ilmu Komputer",
        documentType: "Permohonan Surat Keterangan Aktif",
        submittedAt: "25 Feb 2026, 14:30",
        status: "Selesai",
        trackingId: "HYD-2026-002",
    },
    {
        id: "doc-3",
        destinationName: "Dekanat Fakultas MIPA",
        documentType: "Pengajuan Beasiswa",
        submittedAt: "24 Feb 2026, 11:00",
        status: "Selesai",
        trackingId: "HYD-2026-003",
    },
    {
        id: "doc-4",
        destinationName: "Biro Akademik Universitas",
        documentType: "Permohonan Legalisir Ijazah",
        submittedAt: "23 Feb 2026, 08:45",
        status: "Diproses",
        trackingId: "HYD-2026-004",
    },
    {
        id: "doc-5",
        destinationName: "Tata Usaha Matematika",
        documentType: "Pengajuan Cuti Akademik",
        submittedAt: "20 Feb 2026, 16:00",
        status: "Selesai",
        trackingId: "HYD-2026-005",
    },
];

export const adminIncomingDocuments: AdminDocument[] = [
    {
        id: "adoc-1",
        studentName: "Ahmad Fauzan",
        nim: "H1101221001",
        documentType: "Surat Pengantar Penelitian",
        submittedAt: "26 Feb 2026, 09:15",
        status: "Baru",
        trackingId: "HYD-2026-001",
    },
    {
        id: "adoc-2",
        studentName: "Siti Rahmawati",
        nim: "H1101221042",
        documentType: "Permohonan Transkrip Nilai",
        submittedAt: "26 Feb 2026, 10:22",
        status: "Baru",
        trackingId: "HYD-2026-006",
    },
    {
        id: "adoc-3",
        studentName: "Budi Santoso",
        nim: "H1101221078",
        documentType: "Pengajuan Sidang Skripsi",
        submittedAt: "25 Feb 2026, 15:40",
        status: "Baru",
        trackingId: "HYD-2026-007",
    },
    {
        id: "adoc-4",
        studentName: "Dewi Lestari",
        nim: "H1101221023",
        documentType: "Permohonan Surat PKL",
        submittedAt: "25 Feb 2026, 13:10",
        status: "Baru",
        trackingId: "HYD-2026-008",
    },
    {
        id: "adoc-5",
        studentName: "Rizky Pratama",
        nim: "H1101221055",
        documentType: "Pengajuan Penggantian Dosen PA",
        submittedAt: "24 Feb 2026, 09:00",
        status: "Baru",
        trackingId: "HYD-2026-009",
    },
];

export const adminHistoryDocuments: AdminDocument[] = [
    {
        id: "ahist-1",
        studentName: "Nurhaliza Putri",
        nim: "H1101221012",
        documentType: "Permohonan Surat Keterangan Aktif",
        submittedAt: "25 Feb 2026, 14:30",
        status: "Selesai",
        trackingId: "HYD-2026-002",
    },
    {
        id: "ahist-2",
        studentName: "Arif Wibowo",
        nim: "H1101221034",
        documentType: "Pengajuan Beasiswa",
        submittedAt: "24 Feb 2026, 11:00",
        status: "Diproses",
        trackingId: "HYD-2026-003",
    },
    {
        id: "ahist-3",
        studentName: "Maya Indrawati",
        nim: "H1101221067",
        documentType: "Permohonan Legalisir Ijazah",
        submittedAt: "23 Feb 2026, 08:45",
        status: "Selesai",
        trackingId: "HYD-2026-004",
    },
    {
        id: "ahist-4",
        studentName: "Fajar Nugroho",
        nim: "H1101221089",
        documentType: "Pengajuan Cuti Akademik",
        submittedAt: "20 Feb 2026, 16:00",
        status: "Diproses",
        trackingId: "HYD-2026-005",
    },
    {
        id: "ahist-5",
        studentName: "Indah Permatasari",
        nim: "H1101221093",
        documentType: "Surat Rekomendasi Dosen",
        submittedAt: "18 Feb 2026, 10:30",
        status: "Selesai",
        trackingId: "HYD-2026-010",
    },
];
