import type { Destination, StudentDocument, AdminDocument } from "./types";

export const destinations: Destination[] = [
    {
        id: "dest-1",
        categoryCode: "LPPM-01",
        name: "Lembaga Penelitian dan Pengabdian",
        faculty: "Lembaga Universitas",
        description: "Pusat penerimaan dokumen penelitian dan pengabdian masyarakat.",
        documentCount: 24,
        status: "open",
        acceptedDocuments: ["Proposal Penelitian", "Laporan Akhir Pengabdian", "Paten/HKI"],
    },
    {
        id: "dest-2",
        categoryCode: "TU-KOM-02",
        name: "Tata Usaha Ilmu Komputer",
        faculty: "Fakultas MIPA",
        description: "Administrasi akademik program studi Ilmu Komputer",
        documentCount: 12,
        status: "open",
        acceptedDocuments: ["KRS/Tahunan", "Surat Keterangan Aktif", "Transkrip Sementara"],
    },
    {
        id: "dest-3",
        categoryCode: "DEK-MIPA-03",
        name: "Dekanat Fakultas MIPA",
        faculty: "Fakultas MIPA",
        description: "Kantor Dekan dan Wakil Dekan Fakultas MIPA",
        documentCount: 5,
        status: "closed",
        acceptedDocuments: ["Pengajuan Beasiswa", "Surat Izin PKL", "Lembar Pengesahan"],
    },
    {
        id: "dest-4",
        categoryCode: "BAK-04",
        name: "Biro Administrasi Akademik",
        faculty: "Rektorat",
        description: "Biro Administrasi Akademik dan Kemahasiswaan",
        documentCount: 19,
        status: "open",
        acceptedDocuments: ["Legalisir Ijazah", "Surat Cuti Akademik", "Pencetakan KTM"],
    },
    {
        id: "dest-5",
        categoryCode: "LAB-ICT-05",
        name: "Laboratorium ICT",
        faculty: "Fakultas MIPA",
        description: "Pusat penelitian Teknologi Informasi dan Komunikasi",
        documentCount: 8,
        status: "open",
        acceptedDocuments: ["Peminjaman Alat", "Akses Server", "Sertifikasi IT"],
    },
    {
        id: "dest-6",
        categoryCode: "PERPUS-06",
        name: "Perpustakaan Pusat",
        faculty: "Universitas",
        description: "Layanan administrasi keanggotaan dan bebas pustaka",
        documentCount: 31,
        status: "open",
        acceptedDocuments: ["Bebas Pustaka", "Keanggotaan Baru", "Denda Buku"],
    },
    {
        id: "dest-7",
        categoryCode: "FT-TU-07",
        name: "Tata Usaha Teknik Sipil",
        faculty: "Fakultas Teknik",
        description: "Layanan mahasiswa jurusan Teknik Sipil",
        documentCount: 15,
        status: "closed",
        acceptedDocuments: ["Laporan Praktek", "Yudisium", "Cuti Studi"],
    },
    {
        id: "dest-8",
        categoryCode: "FK-ADM-08",
        name: "Admin Fakultas Kedokteran",
        faculty: "Fakultas Kedokteran",
        description: "Layanan administrasi pendidikan dokter",
        documentCount: 42,
        status: "open",
        acceptedDocuments: ["Izin Koas", "Kelengkapan UKMPPD", "Surat Keterangan"],
    },
];

export const studentDocuments: StudentDocument[] = [
    {
        id: "doc-1",
        destinationName: "LPPM Universitas",
        documentType: "Surat Pengantar Penelitian",
        submittedAt: "26 Feb 2026, 09:15",
        status: "Diproses",
        trackingId: "HYD-2026-001",
    },
    {
        id: "doc-2",
        destinationName: "Tata Usaha Ilmu Komputer",
        documentType: "Permohonan Surat Keterangan Aktif",
        submittedAt: "25 Feb 2026, 14:30",
        status: "Selesai",
        trackingId: "HYD-2026-002",
    },
    {
        id: "doc-3",
        destinationName: "Dekanat Fakultas MIPA",
        documentType: "Pengajuan Beasiswa",
        submittedAt: "24 Feb 2026, 11:00",
        status: "Selesai",
        trackingId: "HYD-2026-003",
    },
    {
        id: "doc-4",
        destinationName: "Biro Akademik Universitas",
        documentType: "Permohonan Legalisir Ijazah",
        submittedAt: "23 Feb 2026, 08:45",
        status: "Diproses",
        trackingId: "HYD-2026-004",
    },
    {
        id: "doc-5",
        destinationName: "Tata Usaha Matematika",
        documentType: "Pengajuan Cuti Akademik",
        submittedAt: "20 Feb 2026, 16:00",
        status: "Selesai",
        trackingId: "HYD-2026-005",
    },
    {
        id: "doc-6",
        destinationName: "Biro Administrasi Akademik",
        documentType: "Pencetakan KTM Baru",
        submittedAt: "19 Feb 2026, 10:20",
        status: "Diproses",
        trackingId: "HYD-2026-006",
    },
    {
        id: "doc-7",
        destinationName: "Perpustakaan Pusat",
        documentType: "Surat Bebas Pustaka",
        submittedAt: "18 Feb 2026, 09:00",
        status: "Selesai",
        trackingId: "HYD-2026-007",
    },
    {
        id: "doc-8",
        destinationName: "Fakultas Teknik",
        documentType: "Pengajuan Kerja Praktek",
        submittedAt: "17 Feb 2026, 13:45",
        status: "Selesai",
        trackingId: "HYD-2026-008",
    },
    {
        id: "doc-9",
        destinationName: "Tata Usaha Ilmu Komputer",
        documentType: "Lembar Pengesahan Skripsi",
        submittedAt: "16 Feb 2026, 11:30",
        status: "Selesai",
        trackingId: "HYD-2026-009",
    },
    {
        id: "doc-10",
        destinationName: "Laboratorium ICT",
        documentType: "Izin Akses Server Data",
        submittedAt: "15 Feb 2026, 15:10",
        status: "Diproses",
        trackingId: "HYD-2026-010",
    },
    {
        id: "doc-11",
        destinationName: "LPPM Universitas",
        documentType: "Laporan Kemajuan KKN",
        submittedAt: "14 Feb 2026, 08:30",
        status: "Selesai",
        trackingId: "HYD-2026-011",
    },
    {
        id: "doc-12",
        destinationName: "Dekanat Fakultas MIPA",
        documentType: "Surat Izin Lomba Nasional",
        submittedAt: "13 Feb 2026, 14:00",
        status: "Selesai",
        trackingId: "HYD-2026-012",
    },
    {
        id: "doc-13",
        destinationName: "Biro Kamahasiswaan",
        documentType: "Pengajuan Dana Hibah UKM",
        submittedAt: "12 Feb 2026, 10:00",
        status: "Diproses",
        trackingId: "HYD-2026-013",
    },
    {
        id: "doc-14",
        destinationName: "Tata Usaha Ilmu Komputer",
        documentType: "KRS Semester Genap 2026",
        submittedAt: "11 Feb 2026, 09:15",
        status: "Selesai",
        trackingId: "HYD-2026-014",
    },
    {
        id: "doc-15",
        destinationName: "Pusat Bahasa",
        documentType: "Sertifikat TOEFL",
        submittedAt: "10 Feb 2026, 16:30",
        status: "Selesai",
        trackingId: "HYD-2026-015",
    },
    {
        id: "doc-16",
        destinationName: "Fakultas Ekonomi",
        documentType: "Transkrip Nilai Semester 5",
        submittedAt: "09 Feb 2026, 11:45",
        status: "Diproses",
        trackingId: "HYD-2026-016",
    },
    {
        id: "doc-17",
        destinationName: "Poliklinik Kampus",
        documentType: "Surat Keterangan Sehat",
        submittedAt: "08 Feb 2026, 08:45",
        status: "Selesai",
        trackingId: "HYD-2026-017",
    },
    {
        id: "doc-18",
        destinationName: "Biro Akademik",
        documentType: "Verifikasi Ijazah Hilang",
        submittedAt: "07 Feb 2026, 13:20",
        status: "Diproses",
        trackingId: "HYD-2026-018",
    },
    {
        id: "doc-19",
        destinationName: "Lab Fisika Dasar",
        documentType: "Modul Praktikum Optik",
        submittedAt: "06 Feb 2026, 15:40",
        status: "Selesai",
        trackingId: "HYD-2026-019",
    },
    {
        id: "doc-20",
        destinationName: "Sekretariat Rektor",
        documentType: "Undangan Audiensi BEM",
        submittedAt: "05 Feb 2026, 10:10",
        status: "Selesai",
        trackingId: "HYD-2026-020",
    },
];

export const adminIncomingDocuments: AdminDocument[] = [
    {
        id: "adoc-1",
        studentName: "Ahmad Fauzan",
        nim: "H1101221001",
        documentType: "Surat Pengantar Penelitian",
        submittedAt: "26 Feb 2026, 09:15",
        status: "Baru",
        trackingId: "HYD-2026-001",
    },
    {
        id: "adoc-2",
        studentName: "Siti Rahmawati",
        nim: "H1101221042",
        documentType: "Permohonan Transkrip Nilai",
        submittedAt: "26 Feb 2026, 10:22",
        status: "Baru",
        trackingId: "HYD-2026-006",
    },
    {
        id: "adoc-3",
        studentName: "Budi Santoso",
        nim: "H1101221078",
        documentType: "Pengajuan Sidang Skripsi",
        submittedAt: "25 Feb 2026, 15:40",
        status: "Baru",
        trackingId: "HYD-2026-007",
    },
    {
        id: "adoc-4",
        studentName: "Dewi Lestari",
        nim: "H1101221023",
        documentType: "Permohonan Surat PKL",
        submittedAt: "25 Feb 2026, 13:10",
        status: "Baru",
        trackingId: "HYD-2026-008",
    },
    {
        id: "adoc-5",
        studentName: "Rizky Pratama",
        nim: "H1101221055",
        documentType: "Pengajuan Penggantian Dosen PA",
        submittedAt: "24 Feb 2026, 09:00",
        status: "Baru",
        trackingId: "HYD-2026-009",
    },
    {
        id: "adoc-6",
        studentName: "Lia Amalia",
        nim: "H1101221088",
        documentType: "Surat Izin Cuti Hamil",
        submittedAt: "24 Feb 2026, 11:30",
        status: "Baru",
        trackingId: "HYD-2026-011",
    },
    {
        id: "adoc-7",
        studentName: "Dedi Setiadi",
        nim: "H1101221099",
        documentType: "Permohonan Pindah Prodi",
        submittedAt: "24 Feb 2026, 14:15",
        status: "Diproses",
        trackingId: "HYD-2026-012",
    },
    {
        id: "adoc-8",
        studentName: "Eka Putri",
        nim: "H1101221111",
        documentType: "Laporan PKL Industri",
        submittedAt: "24 Feb 2026, 16:45",
        status: "Baru",
        trackingId: "HYD-2026-013",
    },
];

export const adminHistoryDocuments: AdminDocument[] = [
    {
        id: "ahist-1",
        studentName: "Nurhaliza Putri",
        nim: "H1101221012",
        documentType: "Permohonan Surat Keterangan Aktif",
        submittedAt: "25 Feb 2026, 14:30",
        status: "Selesai",
        trackingId: "HYD-2026-002",
    },
    {
        id: "ahist-2",
        studentName: "Arif Wibowo",
        nim: "H1101221034",
        documentType: "Pengajuan Beasiswa",
        submittedAt: "24 Feb 2026, 11:00",
        status: "Diproses",
        trackingId: "HYD-2026-003",
    },
    {
        id: "ahist-3",
        studentName: "Maya Indrawati",
        nim: "H1101221067",
        documentType: "Permohonan Legalisir Ijazah",
        submittedAt: "23 Feb 2026, 08:45",
        status: "Selesai",
        trackingId: "HYD-2026-004",
    },
    {
        id: "ahist-4",
        studentName: "Fajar Nugroho",
        nim: "H1101221089",
        documentType: "Pengajuan Cuti Akademik",
        submittedAt: "20 Feb 2026, 16:00",
        status: "Diproses",
        trackingId: "HYD-2026-005",
    },
    {
        id: "ahist-5",
        studentName: "Indah Permatasari",
        nim: "H1101221093",
        documentType: "Surat Rekomendasi Dosen",
        submittedAt: "18 Feb 2026, 10:30",
        status: "Selesai",
        trackingId: "HYD-2026-010",
    },
    {
        id: "ahist-6",
        studentName: "Guntur Pratama",
        nim: "H1101221122",
        documentType: "Bebas Pustaka",
        submittedAt: "17 Feb 2026, 09:15",
        status: "Selesai",
        trackingId: "HYD-2026-014",
    },
    {
        id: "ahist-7",
        studentName: "Sari Wahyuni",
        nim: "H1101221133",
        documentType: "Transkrip Akhir",
        submittedAt: "16 Feb 2026, 13:40",
        status: "Selesai",
        trackingId: "HYD-2026-015",
    },
    {
        id: "ahist-8",
        studentName: "Rudi Hartono",
        nim: "H1101221144",
        documentType: "Yudisium",
        submittedAt: "15 Feb 2026, 15:55",
        status: "Selesai",
        trackingId: "HYD-2026-016",
    },
    {
        id: "ahist-9",
        studentName: "Nina Kartika",
        nim: "H1101221155",
        documentType: "Pengesahan Ijazah",
        submittedAt: "14 Feb 2026, 10:20",
        status: "Selesai",
        trackingId: "HYD-2026-017",
    },
    {
        id: "ahist-10",
        studentName: "Tomi Wijaya",
        nim: "H1101221166",
        documentType: "Sertifikat TOEFL",
        submittedAt: "13 Feb 2026, 08:30",
        status: "Selesai",
        trackingId: "HYD-2026-018",
    },
];
